### PR TITLE
fix deprecations, do not use string.data

### LINKED ISSUE #80: needs update for string.data changes
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/tanmaykm/ProtoBuf.jl/blob/1477fa6b460f3b5fc5c5eacdf0d3821dc4f0eeb6/test/testcodec.jl#L217

### PR DESCRIPTION
**Pull request by tanmaykm**
fixes #80

### CODE REVIEW

File: test/testcodec.jl [hunk 1]
```diff
@@ -214,7 +214,7 @@ function test_repeats()
 
     print_hdr("repeated int64")
     for idx in 1:100
-        testval.val = convert(Array{Int64,1}, randstring(50).data)
+        testval.val = convert(Array{Int64,1}, Vector{UInt8}(randstring(50)))
```
Comment (JeffBezanson) [inline test/testcodec.jl]: This could also be done with `collect(Int64, randstring(50))`.

Comment (tanmaykm) [inline test/testcodec.jl]: Ah, yes. Thanks.

File: REQUIRE [hunk 2]
```diff
@@ -1,2 +1,2 @@
 julia 0.4.0
-Compat 0.8.5
+Compat 0.10.0
```
Comment (tkelman) [inline REQUIRE]: too conservative - 0.9.5 introduced `take!`, and you're not using transcode or `.=`
