### PR TITLE
fix #36: Adds '_pb' Postfix to all Module Names

### LINKED ISSUE #36: "ERROR: invalid redefinition of constant" when package name matches a message name.
protobuf [Foo.proto]:
```protobuf
package PB.Foo;

message Foo {
  required string bar = 1;
}
```

julia [PB.jl]:
```julia
module PB
  module Foo
    include("Foo_pb.jl")
  end
end
```

julia [Foo_pb.jl]:
```julia
using ProtoBuf
import ProtoBuf.meta

type Foo
    bar::String
    Foo() = (o=new(); fillunset(o); o)
end #type Foo
const __req_Foo = Symbol[:bar]
meta(t::Type{Foo}) = meta(t, __req_Foo, ProtoBuf.DEF_FNUM, ProtoBuf.DEF_VAL, true, ProtoBuf.DEF_PACK, ProtoBuf.DEF_WTYPES)

export Foo
```

When trying `using PB` the result is "ERROR: invalid redefinition of constant".

### PR DESCRIPTION
**Pull request by sbchisholm**
This assists in avoid name collisions between packages/modules and messages/types. This is a possible solution for issue #36.

### CODE REVIEW

**Comment by tanmaykm** [comment]
Thanks for the PR. 

It will be sad to have all modules renamed. But the implementation suggested in #36 is probably more complicated.

Since this will be a breaking change, I think we should at least have a command line option for now to switch to this form only when required.

**Comment by sbchisholm** [comment]
What about instead of a command line option, we use a environment variable?  JULIA_PROTOBUF_MODULE_POSTFIX=1 or 0 to enable or disable the option.  We can leave it disabled by default to maintain backwards compatibility.

**Comment by tanmaykm** [comment]
Yes, that seems better.

**Comment by sbchisholm** [comment]
Anything else to address before we merge and tag a new release?

File: src/gen.jl [hunk 1]
```diff
@@ -24,6 +24,8 @@ const _keywords = [
     "bitstype", "do", "baremodule", "importall", "immutable"
 ]
 
+_module_prefix = false
```
Comment (tanmaykm) [inline src/gen.jl]: should this be called `_module_postfix`?

**Comment by tanmaykm** [comment]
Thanks. LGTM!
I think we can tag a new release with this.
Please squash the commits.

**Comment by sbchisholm** [comment]
Version `v"0.1.3"` make sense, since we didn't break backwards compatibility?   Should we mark #36 as closed with this?

**Comment by tanmaykm** [comment]
Yes, `0.1.3` should be fine I think.
I think we can mark #36 as closed too.

**Comment by sbchisholm** [comment]
Thanks for helping moving this along quickly.
